#%RAML 1.0 DataType

properties:
  accountNumber :
    type: string
    required: true
    example: "2456178687"
  amountToBeDeposit :
    type: string
    required: true
    example: "successfully deposit amount"