#%RAML 1.0 DataType

properties:
  bankName:
    type: string
    required: true
    example: "SBI" 
  customerName:
    type: string
    required: true
    example: "raghu"
  pan:
    type: string
    required: true
    example: "AQYPK8711A"
  adhar:
    type: string
    required: true
    example: "67564362789"
  accountNumber:
    type: string
    required: true
    example: "SBI7645387290"
  mailID:
    type: string
    required: true
    example: "raghu@gmail.com"
  contactNumber:
    type: string
    required: true
    example: "9550263124"
  ifscCode:
    type: string
    required: true
    example: "IFSC9878"




     

  


